[project]
name = "data-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.6.12",
    "pytest>=8.3.5",
    "ruff>=0.11.7",
]
